initialDelay: 1
server:
  port: 25565
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/netmusic2?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true
