workingDir: /root/workingDir
initialDelay: 1
main: true
server:
  port: 25565
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/netmusic?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true

powerjob:
  worker:
    # akka 工作端口，可选，默认 27777
    port: 27777
    # 接入应用名称，用于分组隔离，推荐填写 本 Java 项目名称
    app-name: my-powerjob-worker
    # 单个任务追加的工作流上下文最大长度，超过这个长度的会被直接丢弃，默认值 8192
    max-appended-wf-context-length: 4096
    # 同时运行的重量级任务数量上限
    max-heavyweight-task-num: 64
    # 同时运行的轻量级任务数量上限
    max-lightweight-task-num: 1024
    # 任务返回结果信息的最大长度，超过这个长度的信息会被截断，默认值 8192
    max-result-length: 4096
    # 通讯协议，4.3.0 开始支持 HTTP 和 AKKA 两种协议，官方推荐使用 HTTP 协议（注意 server 和 worker 都要开放相应端口）
    protocol: http
    # 调度服务器地址，IP:Port 或 域名，多值逗号分隔
    server-address: 127.0.0.1:7700,127.0.0.1:7701
    # 持久化方式，可选，默认 disk
    store-strategy: disk
    # pjb密码
    password: 密码